x-base: &base
  image: chatwoot/chatwoot:latest
  env_file: .env
  volumes:
    - storage_data:/app/storage
    - ./vendor/db:/app/vendor/db
    - ./patches/vite/assets/typing-BSHE76c6.js:/app/public/vite/assets/typing-BSHE76c6.js:ro
    - ./patches/vite/assets/typing-v2.js:/app/public/vite/assets/typing-v2.js:ro
    - ./patches/vite/assets/utils.esm-qHqIGgqd.js:/app/public/vite/assets/utils.esm-qHqIGgqd.js:ro
    - ./patches/vite/assets/Messages-v2.js:/app/public/vite/assets/Messages-v2.js:ro
    - ./patches/vite/assets/widget-v2.js:/app/public/vite/assets/widget-v2.js:ro
    - ./patches/vite/.vite/manifest.json:/app/public/vite/.vite/manifest.json:ro
    - ./patches/packs/js/sdk.js:/app/public/packs/js/sdk.js:ro
    - ./patches/packs/js/sdk.js.gz:/app/public/packs/js/sdk.js.gz:ro
    - ./patches/packs/js/sdk.js.br:/app/public/packs/js/sdk.js.br:ro
    - ./patches/packs/js/sdk-v2.js:/app/public/packs/js/sdk-v2.js:ro
    - ./patches/packs/js/sdk-v2.js.gz:/app/public/packs/js/sdk-v2.js.gz:ro
    - ./patches/packs/js/sdk-v2.js.br:/app/public/packs/js/sdk-v2.js.br:ro
    - ./app/models/channel/web_widget.rb:/app/app/models/channel/web_widget.rb:ro
  network_mode: host

services:
  rails:
    <<: *base
    container_name: chatwoot-rails
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - PORT=3150
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3150', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    container_name: chatwoot-sidekiq
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

volumes:
  storage_data:
